language: python

cache:
  - pip
  - directories:
    - $HOME/Library/Caches/pip
    - $HOME/Download

matrix:
  include:
    - name: "Python 3.6 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.6
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.6.8/python-3.6.8-macosx10.6.pkg
        PYTHON_INSTALLER_MD5: eb1a23d762946329c2aa3448d256d421
        PATH: /Users/travis/Library/Python/3.6/bin:$PATH
    - name: "Python 3.7 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.7
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.7.6/python-3.7.6-macosx10.6.pkg
        PYTHON_INSTALLER_MD5: 0dfc4cdd9404cf0f5274d063eca4ea71
        PATH: /Users/travis/Library/Python/3.7/bin:$PATH
    - name: "Python 3.8 (OS X)"
      os: osx
      osx_image: xcode8
      language: generic
      env:
        PYTHON: python3.8
        PYTHON_INSTALLER_URL: https://www.python.org/ftp/python/3.8.1/python-3.8.1-macosx10.9.pkg
        PYTHON_INSTALLER_MD5: d1b09665312b6b1f4e11b03b6a4510a3
        PATH: /Users/travis/Library/Python/3.8/bin:$PATH
    - name: "Python 3.5 (Linux)"
      os: linux
      dist: xenial
      python: "3.5"
    - name: "Python 3.6 (Linux)"
      os: linux
      dist: xenial
      python: "3.6"
    - name: "Python 3.7 (Linux)"
      os: linux
      dist: xenial
      python: "3.7"
    - name: "Python 3.8 (Linux)"
      os: linux
      dist: xenial
      python: "3.8"

git:
  depth: 1

install:
  - ./ci/travis-install.sh

script:
  - export SOURCE_DATE_EPOCH="$(git log -1 --date=unix --format='format:%ct' rtmidi/release.py)"
  - ${PYTHON:-python} setup.py release

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ./ci/travis-deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
